import { MetadataRoute } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://aryanrawther.com";

const staticRoutes: { url: string; changeFrequency: "monthly" | "yearly" | "weekly"; priority: number }[] = [
  { url: "/", changeFrequency: "weekly", priority: 1.0 },
  { url: "/about", changeFrequency: "monthly", priority: 0.9 },
  { url: "/about/beyond-work", changeFrequency: "monthly", priority: 0.6 },
  { url: "/services", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/ai-automation-consulting", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/ai-integration", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/ai-voice-agents", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/seo-services", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/web-development", changeFrequency: "monthly", priority: 0.9 },
  { url: "/services/saas-development", changeFrequency: "monthly", priority: 0.9 },
  { url: "/products", changeFrequency: "monthly", priority: 0.8 },
  { url: "/products/speclens-ai", changeFrequency: "monthly", priority: 0.8 },
  { url: "/products/mediamitra", changeFrequency: "monthly", priority: 0.7 },
  { url: "/products/geo-checker", changeFrequency: "monthly", priority: 0.7 },
  { url: "/case-studies", changeFrequency: "monthly", priority: 0.8 },
  { url: "/case-studies/seo-internal-linking-ai-agent", changeFrequency: "yearly", priority: 0.7 },
  { url: "/case-studies/autonomous-inbound-email-agent", changeFrequency: "yearly", priority: 0.7 },
  { url: "/case-studies/speclens-ai-procurement-saas", changeFrequency: "yearly", priority: 0.7 },
  { url: "/case-studies/photoshoprequest-ai-editor", changeFrequency: "yearly", priority: 0.7 },
  { url: "/case-studies/healthcare-rcm-automation", changeFrequency: "yearly", priority: 0.7 },
  { url: "/case-studies/combinehealth-seo-redesign", changeFrequency: "yearly", priority: 0.7 },

  { url: "/blog", changeFrequency: "weekly", priority: 0.8 },
  { url: "/resources", changeFrequency: "monthly", priority: 0.7 },
  { url: "/resources/ai-automation-guide-for-business", changeFrequency: "monthly", priority: 0.7 },
  { url: "/resources/geo-optimisation-guide", changeFrequency: "monthly", priority: 0.7 },
  { url: "/resources/technical-seo-audit-checklist", changeFrequency: "monthly", priority: 0.6 },
  { url: "/resources/ai-voice-agents-explainer", changeFrequency: "monthly", priority: 0.6 },
  { url: "/resources/nextjs-saas-architecture", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary", changeFrequency: "monthly", priority: 0.7 },
  // AI & Automation
  { url: "/glossary/agentic-ai", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/ai-agent", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/ai-orchestration", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/context-window", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/fine-tuning", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/function-calling", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/hallucination", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/large-language-model", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/prompt-engineering", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/rag", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/rcm", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/vector-database", changeFrequency: "monthly", priority: 0.6 },
  // SEO & GEO
  { url: "/glossary/ai-overviews", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/core-web-vitals", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/e-e-a-t", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/geo", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/llms-txt", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/programmatic-seo", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/search-intent", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/semantic-seo", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/structured-data", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/technical-seo", changeFrequency: "monthly", priority: 0.6 },
  // AI Voice
  { url: "/glossary/ivr", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/speech-to-text", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/text-to-speech", changeFrequency: "monthly", priority: 0.6 },
  // Web & SaaS
  { url: "/glossary/api", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/headless-architecture", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/multi-tenant-saas", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/mvp", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/server-side-rendering", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/technical-co-founder", changeFrequency: "monthly", priority: 0.6 },
  { url: "/glossary/webhook", changeFrequency: "monthly", priority: 0.6 },
  { url: "/faq", changeFrequency: "monthly", priority: 0.7 },
  { url: "/process", changeFrequency: "monthly", priority: 0.7 },
  { url: "/testimonials", changeFrequency: "monthly", priority: 0.6 },
  { url: "/contact", changeFrequency: "monthly", priority: 0.8 },
  { url: "/industries/saas", changeFrequency: "monthly", priority: 0.6 },
  { url: "/industries/edtech", changeFrequency: "monthly", priority: 0.6 },
  { url: "/industries/healthcare", changeFrequency: "monthly", priority: 0.6 },
  { url: "/industries/ecommerce", changeFrequency: "monthly", priority: 0.6 },
  { url: "/industries/startups", changeFrequency: "monthly", priority: 0.6 },
  { url: "/location/bangalore", changeFrequency: "monthly", priority: 0.6 },
  { url: "/location/india", changeFrequency: "monthly", priority: 0.6 },
  { url: "/location/remote", changeFrequency: "monthly", priority: 0.6 },
  { url: "/privacy-policy", changeFrequency: "yearly", priority: 0.2 },
  { url: "/terms-of-service", changeFrequency: "yearly", priority: 0.2 },
  { url: "/sitemap", changeFrequency: "monthly", priority: 0.3 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  return staticRoutes.map((route) => ({
    url: `${siteUrl}${route.url}`,
    lastModified: new Date(),
    changeFrequency: route.changeFrequency,
    priority: route.priority,
  }));
}
